# Generated by Django 5.2.9 on 2025-12-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoraGenProductSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productSeed', models.CharField(max_length=255, unique=True, verbose_name='产品种子 (Product Seed)')),
                ('promptB', models.TextField(verbose_name='提示词B (Prompt B)')),
            ],
            options={
                'verbose_name': 'SoraGen 产品种子',
                'verbose_name_plural': 'SoraGen 产品种子',
            },
        ),
        migrations.CreateModel(
            name='SoraGenStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=255, unique=True, verbose_name='风格 (Style)')),
                ('promptA', models.TextField(verbose_name='提示词A (Prompt A)')),
            ],
            options={
                'verbose_name': 'SoraGen 风格',
                'verbose_name_plural': 'SoraGen 风格',
            },
        ),
    ]
